version: '3'
services:
  crawler:
    build:
      context: ./crawler
    depends_on:
      - rabbitmq
      - redis
    environment:
      - CRAWLER_INPUT_QUEUE=${CRAWLER_INPUT_QUEUE}
      - CRAWLER_OUTPUT_QUEUE=${CRAWLER_OUTPUT_QUEUE}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - EXTRATO_CLUBE_API=${EXTRATO_CLUBE_API}
  api:
    build:
      context: ./api
    ports:
      - '3000:${API_PORT}'
    depends_on:
      - rabbitmq
      - elasticsearch
    environment:
      - CRAWLER_INPUT_QUEUE=${CRAWLER_INPUT_QUEUE}
      - CRAWLER_OUTPUT_QUEUE=${CRAWLER_OUTPUT_QUEUE}
      - API_PORT=${API_PORT}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - ELASTIC_SEARCH_URI=${ELASTIC_SEARCH_URI}
  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    depends_on:
      - api
  rabbitmq:
    image: rabbitmq:3
    ports:
      - '5672:5672'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
  redis:
    image: redis:7.0.12-alpine
    ports:
      - '6379:6379'
