version: '3'
services:
  crawler:
    command: ["npm", "run", "dev"]
    volumes:
      - crawler_node_modules:/app/node_modules
      - ./crawler:/app
  api:
    command: ["npm", "run", "dev"]
    volumes:
      - api_node_modules:/app/node_modules
      - ./api:/app

volumes:
  crawler_node_modules:
  api_node_modules:
