version: '3'
services:
  crawler:
    command: ["npm", "run", "dev"]
    volumes:
      - crawler_node_modules:/app/node_modules
      - ./crawler:/app
  api:
    command: ["npm", "run", "dev"]
    volumes:
      - api_node_modules:/app/node_modules
      - ./api:/app
  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./frontend:/app

volumes:
  crawler_node_modules:
  api_node_modules:
  frontend_node_modules:
