version: '3'
services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - '5672:5672'
  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
