version: '3'
services:
  crawler:
    build:
      context: ./crawler
    depends_on:
      - rabbitmq
      - redis
  api:
    build:
      context: ./api
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
      - elasticsearch
  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    depends_on:
      - api
  rabbitmq:
    image: rabbitmq:3
    ports:
      - '5672:5672'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
  redis:
    image: redis:7.0.12-alpine
    ports:
      - '6379:6379'
